export const dishes = [
  {
    id: 1,
    restaurant: "McDonny",
    product: "Small tasty",
    image: "/pics/McDonny/tasty.png",
    cost: 123,
    cartQuantity: 0,
  },
  {
    id: 2,
    restaurant: "McDonny",
    product: "Cheeseburger",
    image: "/pics/McDonny/cheeseburger.jpg",
    cost: 126,
    cartQuantity: 0,
  },
  {
    id: 3,
    restaurant: "McDonny",
    product: "SadMeal",
    image: "/pics/McDonny/sadmeal.jpg",
    cost: 132,
    cartQuantity: 0,
  },
  {
    id: 4,
    restaurant: "McDonny",
    product: "McFurry",
    image: "/pics/McDonny/furry.png",
    cost: 210,
    cartQuantity: 0,
  },
  {
    id: 5,
    restaurant: "McDonny",
    product: "McMafia",
    image: "/pics/McDonny/mafia.jpg",
    cost: 155,
    cartQuantity: 0,
  },
  {
    id: 6,
    restaurant: "CFK",
    product: "Wings",
    image: "/pics/CFK/Wings.jpg",
    cost: 213,
    cartQuantity: 0,
  },
  {
    id: 7,
    restaurant: "CFK",
    product: "Strips",
    image: "/pics/CFK/strips.png",
    cost: 203,
    cartQuantity: 0,
  },
  {
    id: 8,
    restaurant: "CFK",
    product: "Bucket",
    image: "/pics/CFK/bucket.png",
    cost: 534,
    cartQuantity: 0,
  },
  {
    id: 9,
    restaurant: "CFK",
    product: "Legs",
    image: "/pics/CFK/legs.png",
    cost: 128,
    cartQuantity: 0,
  },
  {
    id: 10,
    restaurant: "CFK",
    product: "Chickenburger",
    image: "/pics/CFK/chicken.png",
    cost: 215,
    cartQuantity: 0,
  },
  {
    id: 11,
    restaurant: "Uncle John's",
    product: "Mozarella Sticks",
    image: "/pics/Johns/sticks.png",
    cost: 105,
    cartQuantity: 0,
  },
  {
    id: 12,
    restaurant: "Uncle John's",
    product: "Uncledias",
    image: "/pics/Johns/dias.jpg",
    cost: 319,
    cartQuantity: 0,
  },
  {
    id: 13,
    restaurant: "Uncle John's",
    product: "Honey Mustard",
    image: "/pics/Johns/mustard.jpg",
    cost: 30,
    cartQuantity: 0,
  },
  {
    id: 14,
    restaurant: "Uncle John's",
    product: "BBQ Chicken Pizza",
    image: "/pics/Johns/bbq.png",
    cost: 239,
    cartQuantity: 0,
  },
  {
    id: 15,
    restaurant: "Uncle John's",
    product: "Margherita pizza",
    image: "/pics/Johns/margherita.png",
    cost: 192,
    cartQuantity: 0,
  },
  {
    id: 16,
    restaurant: "Sonimod Pizza",
    product: "Carbonara",
    image: "/pics/Sonimod/carbonara.jpg",
    cost: 329,
    cartQuantity: 0,
  },
  {
    id: 17,
    restaurant: "Sonimod Pizza",
    product: "Royal Cheeseburger",
    image: "/pics/Sonimod/royal.jpg",
    cost: 239,
    cartQuantity: 0,
  },
  {
    id: 18,
    restaurant: "Sonimod Pizza",
    product: "Toscana",
    image: "/pics/Sonimod/toscana.png",
    cost: 439,
    cartQuantity: 0,
  },
  {
    id: 19,
    restaurant: "Sonimod Pizza",
    product: "5 Cheese",
    image: "/pics/Sonimod/cheese.png",
    cost: 593,
    cartQuantity: 0,
  },
  {
    id: 20,
    restaurant: "Sonimod Pizza",
    product: "Munich DeLUX",
    image: "/pics/Sonimod/munich.jpg",
    cost: 293,
    cartQuantity: 0,
  },
];
